### ISSUE TITLE
need help tut

### ISSUE THREAD

**Issue by Z4RBH** [SteveJobsnihack/tiktok-get-followers#1]
i am new in this stuff can you help me to get my api ?

**Comment by SteveJobsnihack** [comment]
How can i help you?

**Comment by slarkb** [comment]
> How can i help you?

Traceback (most recent call last):
  File "C:\Users\MSI\Desktop\tiktok-get-followers-main\app.py", line 74, in <module>
    get_followers(0)
  File "C:\Users\MSI\Desktop\tiktok-get-followers-main\app.py", line 57, in get_followers
    for u in r["followers"]:
KeyError: 'followers'

**Comment by SteveJobsnihack** [comment]
@slarkb have you entered a valid user_id and scraptubes_key?

Send me your script https://t.me/SteveJobsnihack and i will debug your code.

**Comment by slarkb** [comment]
> @slarkb have you entered a valid user_id and scraptubes_key?
> 
> Send me your script https://t.me/SteveJobsnihack and i will debug your code.

https://prnt.sc/OeIosWXiBM7e

**Comment by slarkb** [comment]
Does user_id mean tiktok username or in the api?

**Comment by slarkb** [comment]
It still shows error when I applied user under api

**Comment by SteveJobsnihack** [comment]
@slarkb its the user_id is integer value.

**Comment by SteveJobsnihack** [comment]
@slarkb to get the ID from Username use this Script. Just edit the username and your apikey.

import requests

url = "https://scraptubes.p.rapidapi.com/scrape/tiktok/userid"

payload = { "username": "ninogashi" }
headers = {
	"content-type": "application/json",
	"Content-Type": "application/json",
	"X-RapidAPI-Key": "xxx",
	"X-RapidAPI-Host": "scraptubes.p.rapidapi.com"
}

response = requests.post(url, json=payload, headers=headers)

print(response.json())

**Comment by slarkb** [comment]
> @slarkb to get the ID from Username use this Script. Just edit the username and your apikey.
> 
> import requests
> 
> url = "https://scraptubes.p.rapidapi.com/scrape/tiktok/userid"
> 
> payload = { "username": "ninogashi" } headers = { "content-type": "application/json", "Content-Type": "application/json", "X-RapidAPI-Key": "xxx", "X-RapidAPI-Host": "scraptubes.p.rapidapi.com" }
> 
> response = requests.post(url, json=payload, headers=headers)
> 
> print(response.json())

Same error happen

**Comment by slarkb** [comment]
https://pastebin.com/raw/EjE2hg0h

**Comment by SteveJobsnihack** [comment]
@slarkb 

7057041866483050--6

is not a valid userid.

**Comment by slarkb** [comment]
> @slarkb
> 
> 7057041866483050--6
> 
> is not a valid userid.

I know, it's just that I don't want people to know. I don't actually put that. I put the real one

**Comment by SteveJobsnihack** [comment]
@slarkb i can see that your request is working now 😉

**Comment by slarkb** [comment]
> @slarkb i can see that your request is working now 😉

Are you saying that you can see my request on submitting followers of my ID? It still doesn't work by the way.

Traceback (most recent call last):
  File "C:\Users\MSI\Desktop\tiktok-get-followers-main\app.py", line 74, in <module>
    get_followers(0)
  File "C:\Users\MSI\Desktop\tiktok-get-followers-main\app.py", line 72, in get_followers
    get_followers(r["min_time"])
  File "C:\Users\MSI\Desktop\tiktok-get-followers-main\app.py", line 57, in get_followers
    for u in r["followers"]:
KeyError: 'followers'

**Comment by SteveJobsnihack** [comment]
@slarkb Yes i can see that.

**Comment by slarkb** [comment]
> @slarkb Yes i can see that.

I see that you're the one who created the API. Do you have any idea to ge this to work?

**Comment by Z4RBH** [comment]
> How can i help you?

how do i get my api ?

**Comment by SteveJobsnihack** [comment]
@Z4RBH register here https://rapidapi.com/SteveJobsnihack/api/scraptubes

**Comment by SteveJobsnihack** [comment]
@slarkb sure how can I help you bro?

**Comment by slarkb** [comment]
> @slarkb sure how can I help you bro?

I can't get it to work. 
This is the error it gives me:
Traceback (most recent call last):
File "C:\Users\MSI\Desktop\tiktok-get-followers-main\app.py", line 74, in
get_followers(0)
File "C:\Users\MSI\Desktop\tiktok-get-followers-main\app.py", line 72, in get_followers
get_followers(r["min_time"])
File "C:\Users\MSI\Desktop\tiktok-get-followers-main\app.py", line 57, in get_followers
for u in r["followers"]:
KeyError: 'followers'

**Comment by SteveJobsnihack** [comment]
@slarkb use the new script:
https://github.com/SteveJobsnihack/tiktok-get-followers/blob/main/app.py

**Comment by slarkb** [comment]
> @slarkb use the new script: https://github.com/SteveJobsnihack/tiktok-get-followers/blob/main/app.py

It works now, thanks!

**Comment by SteveJobsnihack** [comment]
@slarkb you are welcome bro 💯

**Comment by jefflima1** [comment]
I'm generating users in a .txt file, how to follow on tiktok

**Comment by ngtrgiabao** [comment]
I got this error, How do I fix it

![image](https://github.com/SteveJobsnihack/tiktok-get-followers/assets/95952006/0734e97c-75c9-4742-9577-7e4669c95340)
